# Generated by Django 5.2.3 on 2025-07-29 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_is_featured_property_listing_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_fee', models.DecimalField(decimal_places=2, default=500.0, help_text='Booking fee amount in NPR', max_digits=8)),
                ('visit_fee', models.DecimalField(decimal_places=2, default=200.0, help_text='Visit request fee amount in NPR', max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Booking Fee Configuration',
                'verbose_name_plural': 'Booking Fee Configurations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_type', models.CharField(choices=[('booking', 'Property Booking'), ('visit', 'Property Visit Request')], default='booking', max_length=20)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=20)),
                ('preferred_date', models.DateTimeField(blank=True, null=True)),
                ('message', models.TextField(blank=True, help_text='Additional message or requirements')),
                ('payment_method', models.CharField(choices=[('stripe', 'Stripe (International)'), ('esewa', 'eSewa (Nepal)')], max_length=20)),
                ('transaction_id', models.CharField(max_length=255, unique=True)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(default='completed', max_length=20)),
                ('payment_data', models.JSONField(blank=True, help_text='Store payment gateway response', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Admin Verification'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin verification notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('property_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='properties.property')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Property Booking',
                'verbose_name_plural': 'Property Bookings',
                'ordering': ['-created_at'],
            },
        ),
    ]
