# Generated by Django 5.2.3 on 2025-07-29 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_bookingfee_propertybooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertybooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
