# Generated by Django 5.2.3 on 2025-07-31 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_property_latitude_property_longitude'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyimage',
            options={'ordering': ['-is_primary', 'order']},
        ),
        migrations.AddField(
            model_name='property',
            name='age_of_property',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Age in years', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='balconies',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='facing',
            field=models.CharField(blank=True, choices=[('north', 'North'), ('south', 'South'), ('east', 'East'), ('west', 'West'), ('northeast', 'North-East'), ('northwest', 'North-West'), ('southeast', 'South-East'), ('southwest', 'South-West')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='floor_number',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Floor number (for apartments)', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='furnishing',
            field=models.CharField(choices=[('unfurnished', 'Unfurnished'), ('semi_furnished', 'Semi Furnished'), ('fully_furnished', 'Fully Furnished')], default='unfurnished', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='has_ac',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='has_elevator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='has_garden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='has_gym',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='has_power_backup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='has_security',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='has_swimming_pool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='has_wifi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='parking',
            field=models.CharField(choices=[('none', 'No Parking'), ('street', 'Street Parking'), ('garage', 'Garage'), ('covered', 'Covered Parking'), ('multiple', 'Multiple Spaces')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='parking_spaces',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of parking spaces'),
        ),
        migrations.AddField(
            model_name='property',
            name='pet_friendly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='total_floors',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Total floors in building', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='water_supply',
            field=models.CharField(choices=[('municipality', 'Municipality Water'), ('well', 'Well Water'), ('bore', 'Bore Well'), ('tanker', 'Water Tanker'), ('mixed', 'Mixed Supply')], default='municipality', max_length=20),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='caption',
            field=models.CharField(blank=True, help_text='Optional image description', max_length=255),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Mark as primary display image'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('house', 'House'), ('apartment', 'Apartment'), ('condo', 'Condo'), ('villa', 'Villa'), ('studio', 'Studio'), ('townhouse', 'Townhouse'), ('duplex', 'Duplex'), ('penthouse', 'Penthouse'), ('room', 'Room'), ('flat', 'Flat')], default='house', max_length=20),
        ),
    ]
