# Generated by Django 5.2.3 on 2025-07-31 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_alter_propertyimage_options_property_age_of_property_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyimage',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='property',
            name='age_of_property',
        ),
        migrations.RemoveField(
            model_name='property',
            name='balconies',
        ),
        migrations.RemoveField(
            model_name='property',
            name='facing',
        ),
        migrations.RemoveField(
            model_name='property',
            name='floor_number',
        ),
        migrations.RemoveField(
            model_name='property',
            name='furnishing',
        ),
        migrations.RemoveField(
            model_name='property',
            name='has_ac',
        ),
        migrations.RemoveField(
            model_name='property',
            name='has_elevator',
        ),
        migrations.RemoveField(
            model_name='property',
            name='has_garden',
        ),
        migrations.RemoveField(
            model_name='property',
            name='has_gym',
        ),
        migrations.RemoveField(
            model_name='property',
            name='has_power_backup',
        ),
        migrations.RemoveField(
            model_name='property',
            name='has_security',
        ),
        migrations.RemoveField(
            model_name='property',
            name='has_swimming_pool',
        ),
        migrations.RemoveField(
            model_name='property',
            name='has_wifi',
        ),
        migrations.RemoveField(
            model_name='property',
            name='parking',
        ),
        migrations.RemoveField(
            model_name='property',
            name='parking_spaces',
        ),
        migrations.RemoveField(
            model_name='property',
            name='pet_friendly',
        ),
        migrations.RemoveField(
            model_name='property',
            name='total_floors',
        ),
        migrations.RemoveField(
            model_name='property',
            name='water_supply',
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('house', 'House'), ('apartment', 'Apartment'), ('condo', 'Condo'), ('villa', 'Villa')], default='house', max_length=20),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='caption',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
