# Generated by Django 5.2.3 on 2025-07-31 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_alter_propertyimage_options_and_more'),
    ]

    operations = [
    ]
