# Generated by Django 5.2.3 on 2025-07-31 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_update_caption_field'),
    ]

    operations = [
    ]
