# Generated by Django 5.2.3 on 2025-07-31 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_fix_caption_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertybooking',
            name='additional_properties',
            field=models.TextField(blank=True, help_text='Comma-separated list of additional property IDs for multi-property visits'),
        ),
    ]
