# Generated by Django 5.2.3 on 2025-07-31 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_propertybooking_additional_properties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingfee',
            name='visit_fee',
            field=models.DecimalField(decimal_places=2, default=500.0, help_text='Visit request fee amount in NPR (same as booking fee)', max_digits=8),
        ),
    ]
