# Generated by Django 5.2.3 on 2025-07-31 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_update_booking_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertybooking',
            name='payment_authorized_at',
            field=models.DateTimeField(blank=True, help_text='When payment was authorized (money held)', null=True),
        ),
        migrations.AddField(
            model_name='propertybooking',
            name='payment_captured_at',
            field=models.DateTimeField(blank=True, help_text='When payment was captured (money charged)', null=True),
        ),
        migrations.AddField(
            model_name='propertybooking',
            name='payment_intent_id',
            field=models.CharField(blank=True, help_text='Stripe Payment Intent ID for authorization/capture', max_length=255),
        ),
        migrations.AddField(
            model_name='propertybooking',
            name='payment_refunded_at',
            field=models.DateTimeField(blank=True, help_text='When payment was refunded', null=True),
        ),
        migrations.AlterField(
            model_name='propertybooking',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Payment Pending'), ('authorized', 'Payment Authorized (Hold)'), ('captured', 'Payment Captured (Charged)'), ('failed', 'Payment Failed'), ('refunded', 'Payment Refunded'), ('cancelled', 'Payment Cancelled')], default='pending', max_length=20),
        ),
    ]
