# Generated by Django 5.2.3 on 2025-08-14 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0014_propertybooking_agent_completion_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertybooking',
            name='agent_completion_time',
        ),
        migrations.RemoveField(
            model_name='propertybooking',
            name='customer_completion_time',
        ),
        migrations.RemoveField(
            model_name='propertybooking',
            name='is_eligible_for_booking',
        ),
        migrations.RemoveField(
            model_name='propertybooking',
            name='visit_completed_by_agent',
        ),
        migrations.RemoveField(
            model_name='propertybooking',
            name='visit_completed_by_customer',
        ),
        migrations.RemoveField(
            model_name='propertybooking',
            name='visit_completion_notes',
        ),
        migrations.RemoveField(
            model_name='propertybooking',
            name='visit_status',
        ),
        migrations.AddField(
            model_name='propertybooking',
            name='can_book_after_visit',
            field=models.BooleanField(default=True, help_text='Whether customer can book after completing visit'),
        ),
        migrations.AddField(
            model_name='propertybooking',
            name='visit_completed',
            field=models.BooleanField(default=False, help_text='Whether the visit has been completed'),
        ),
        migrations.AddField(
            model_name='propertybooking',
            name='visit_completed_by',
            field=models.ForeignKey(blank=True, help_text='Agent who marked the visit as completed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_visits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='propertybooking',
            name='booking_deadline',
            field=models.DateTimeField(blank=True, help_text='Deadline for booking after visit completion', null=True),
        ),
        migrations.AlterField(
            model_name='propertybooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='propertybooking',
            name='visit_completed_at',
            field=models.DateTimeField(blank=True, help_text='When the visit was completed', null=True),
        ),
    ]
