# Generated by Django 5.2.3 on 2025-08-13 12:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Real Estate Platform', max_length=100)),
                ('contact_email', models.EmailField(default='admin@realestate.com', max_length=254)),
                ('phone_number', models.CharField(default='+1 (555) 123-4567', max_length=20)),
                ('business_address', models.TextField(default='123 Business St, City')),
                ('site_description', models.TextField(default='Your trusted real estate platform for buying, selling, and renting properties.')),
                ('max_properties_per_agent', models.PositiveIntegerField(default=50, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('max_images_per_property', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('commission_rate', models.DecimalField(decimal_places=2, default=5.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ('booking_expiry_days', models.PositiveIntegerField(default=7, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)])),
                ('allow_registration', models.BooleanField(default=True)),
                ('email_notifications', models.BooleanField(default=True)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('auto_approve_listings', models.BooleanField(default=True)),
                ('require_email_verification', models.BooleanField(default=True)),
                ('smtp_host', models.CharField(default='smtp.gmail.com', max_length=255)),
                ('smtp_port', models.PositiveIntegerField(default=587)),
                ('smtp_use_tls', models.BooleanField(default=True)),
                ('smtp_username', models.CharField(blank=True, max_length=255)),
                ('smtp_password', models.CharField(blank=True, max_length=255)),
                ('from_email', models.EmailField(default='noreply@realestate.com', max_length=254)),
                ('from_name', models.CharField(default='RealEstate Platform', max_length=100)),
                ('session_timeout_minutes', models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(1440)])),
                ('max_login_attempts', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('last_backup', models.DateTimeField(blank=True, null=True)),
                ('storage_used_gb', models.DecimalField(decimal_places=2, default=2.4, max_digits=10)),
                ('uptime_days', models.PositiveIntegerField(default=15)),
                ('uptime_hours', models.PositiveIntegerField(default=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
