# Generated by Django 5.2.3 on 2025-08-13 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
    ]
